name: User Documentation Issue Report
description: File an issue with the user documentation
title: "User Doc Issue"
labels: ["documentation"]
assignees:
  - pbrennan
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this user documentation issue report!
  - type: input
    id: userDocTitle
    attributes:
      label: User Document Title
      description: Please specify the user document title
      placeholder: User Document Title
    validations:
      required: true
  - type: textarea
    id: issueDescription
    attributes:
      label: Description
      description: Please describe the issue with the user document.
      placeholder: Describe the issue!
      value: "Description"
    validations:
      required: true
